app/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms import StringField, HiddenField, SubmitField, BooleanField
from wtforms.validators import ValidationError, Length, Email, DataRequired
from flask_babel import _
from app.models import User

class UserCreateForm(FlaskForm):
    username = StringField(_('Benutzername'), validators=[Length(max=128, message=_('Der Benutzername darf maximal 128 Zeichen lang sein.'))])
    firstname = StringField(_('Vorname'), validators=[Length(max=256, message=_('Maximal 256 Zeichen für Vorname(n) erlaubt.'))])
    lastname = StringField(_('Nachname'), validators=[Length(max=256, message=_('Maximal 256 Zeichen für Nachname(n) erlaubt.'))])
    email = StringField(_('E-Mail-Adresse'), validators=[Length(max=256, message=_('Die E-Mail-Adresse darf maximal 256 Zeichen lang sein.')), Email(_('Ungültige E-Mail-Adresse'))])
    phone = StringField(_('Telefonnummer'), validators=[Length(max=256, message=_('Die Telefonnummer darf maximal 256 Zeichen lang sein.'))])

    is_admin = BooleanField(_('Administrator'), default=False)
    login_allowed = BooleanField(_('Darf sich einloggen'), default=True)
    create_calendar_entry = BooleanField(_('Darf Kalendereinträge anlegen'), default=False)
    create_user = BooleanField(_('Darf Benutzer anlegen'), default=False)
    edit_user = BooleanField(_('Darf Benutzer bearbeiten'), default=False)
    delete_user = BooleanField(_('Darf Benutzer löschen'), default=False)
    edit_rights = BooleanField(_('Darf Benutzerrechte bearbeiten'), default=False)
    create_post = BooleanField(_('Darf Nachrichten schreiben'), default=True)
    edit_foreign_post = BooleanField(_('Darf fremde Nachrichten bearbeiten'), default=False)
    delete_foreign_post = BooleanField(_('Darf fremde Nachrichten löschen'), default=False)

    submit = SubmitField(_('Benutzer anlegen'))

    def validate_username(self, username):
        if username.data.strip(' \t\n\r') == '':
            raise ValidationError(_('Der Benutzername darf nicht leer sein.'))

    def validate_email(self, email):
        if email.data.strip(' \t\n\r') == '':
            raise ValidationError(_('Die E-Mail-Adresse darf nicht leer sein.'))
        check_email = User.query.filter_by(email=email.data).first()
        if check_email is not None:
            self.email.errors.append(_('Diese E-Mail-Adresse ist bereits registriert.'))
            return False
        return True

class UserEditForm(FlaskForm):
    id = HiddenField(validators=[DataRequired(_('Benutzer-ID nicht übertragen.')), ])
    username = StringField(_('Benutzername'), validators=[Length(max=128, message=_('Der Benutzername darf maximal 128 Zeichen lang sein.'))])
    firstname = StringField(_('Vorname'), validators=[Length(max=256, message=_('Maximal 256 Zeichen für Vorname(n) erlaubt.'))])
    lastname = StringField(_('Nachname'), validators=[Length(max=256, message=_('Maximal 256 Zeichen für Nachname(n) erlaubt.'))])
    email = StringField(_('E-Mail-Adresse'), validators=[Length(max=256, message=_('Die E-Mail-Adresse darf maximal 256 Zeichen lang sein.')), Email(_('Ungültige E-Mail-Adresse'))])
    phone = StringField(_('Telefonnummer'), validators=[Length(max=256, message=_('Die Telefonnummer darf maximal 256 Zeichen lang sein.'))])

    avatar = FileField(_('Profilbild'), validators=[FileAllowed(['jpg', 'png'], _('Nur .jpg und .png Dateien erlaubt.'))])
    submit = SubmitField(_('Speichern'))

    def validate(self, extra_validators=None, *args, **kwargs):
        success = super().validate(extra_validators, *args, **kwargs)
        check_username = User.query.filter_by(username=self.username.data).first()
        if check_username is not None:
            if check_username.id != int(self.id.data):
                self.username.errors.append(_('Dieser Benutzername ist bereits vergeben.'))
                success = False
        check_email = User.query.filter_by(email=self.email.data).first()
        if check_email is not None:
            if check_email.id != int(self.id.data):
                self.email.errors.append(_('Diese E-Mail-Adresse ist bereits registriert.'))
                success = False
        return success

    def validate_username(self, username):
        if username.data.strip(' \t\n\r') == '':
            raise ValidationError(_('Der Benutzername darf nicht leer sein.'))

class UserDeleteForm(FlaskForm):
    safety = BooleanField(_('Ich bin mir sicher, dass ich diesen Benutzer löschen möchte.'), validators=[DataRequired(_('Du musst bestätigen, dass du den Benutzer löschen möchtest.'))])
    submitdelete = SubmitField(_('Benutzer löschen'))

class GenerateNew2FAForm(FlaskForm):
    safety2fa = BooleanField(_('Ich bin mir sicher, dass ich ein neues 2FA-Geheimnis generieren möchte.'), validators=[DataRequired(_('Du musst bestätigen, dass du das Geheimnis neu erzeugen möchtest.'))])
    submitnew2fa = SubmitField(_('Neues Geheimnis generieren'))

app/users/__init__.py
from flask import Blueprint

bp = Blueprint('users', __name__)

from app.users import routes

app/users/routes.py
from flask import render_template, redirect, url_for, flash, request, send_from_directory, current_app
from flask_login import login_required, current_user
from flask_babel import _
from app.users import bp
from app import db
from app.models import User, Right
from app.users.forms import UserEditForm, GenerateNew2FAForm, UserDeleteForm, UserCreateForm
from app.email.mail_utils import generate_token, send_email
import sqlalchemy as sa
import pyotp

# USERPAGE
@bp.route('/user', methods=['GET', 'POST'])
@login_required
def userpage():
    id = request.args.get('user')
    rights = get_user_rights()
    # This will be set to true if the user id not found
    # In this case the id will default to the current user
    # This could lead to erroneous deletion or alteration of own user
    error_prevention = False
    # Default: look at oneself
    if not id:
        id = current_user.id
    # Get user data
    user = current_user
    if id != current_user.id:
        user = db.session.scalar(sa.select(User).where(User.id == id))
        if user is None:
            flash(_('Fehler: Benutzer (ID: {}) nicht gefunden.'.format(id)))
            user = current_user
            error_prevention = True
    # User editing
    edit = False
    if request.args.get('edit'):
        edit = True
    editform = None
    change2faform = None
    deleteform = None
    # Check access rights
    if edit and id != current_user.id:
        if rights['edit_users'] == False:
            flash(_('Fehler: Keine Berechtigung zur Bearbeitung von fremden Benutzern.'))
            edit = False
    # Load edit form and populate with default values
    if edit and not error_prevention:
        editform = UserEditForm(
            id=user.id,
            username=user.username,
            firstname=user.firstname,
            lastname=user.lastname,
            email=user.email,
            phone=user.phone
        )
        change2faform = GenerateNew2FAForm()
        if rights['delete_users']:
            deleteform = UserDeleteForm()
    # Save user values
    if editform and editform.submit.data and editform.validate_on_submit():
        user.username = editform.username.data
        user.firstname = editform.firstname.data
        user.lastname = editform.lastname.data
        user.email = editform.email.data
        user.phone = editform.phone.data
        avatar = editform.avatar.data
        if avatar:
            user.set_avatar(avatar)
        flash(_('Benutzerdaten gespeichert.'))
        db.session.commit()
        return redirect(url_for('users.userpage', user=user.id))
    # Generate new 2FA secret
    if change2faform and change2faform.submitnew2fa.data and change2faform.validate_on_submit():
        user.token_2fa = pyotp.random_base32()
        user.is2fa_enabled = False
        flash(_('Neues Geheimnis für die Zwei-Faktor-Authentifizierung generiert. Bitte richte 2FA erneut ein.'))
        db.session.commit()
        return redirect(url_for('auth.setup_2fa', user=user.id))
    # Delete user
    if deleteform and deleteform.submitdelete.data and deleteform.validate_on_submit():
        if user.id == current_user.id:
            flash(_('Fehler: Du kannst dich nicht selbst löschen!'))
            return redirect(url_for('users.userpage', user=user.id))
        # Purge rights
        db.session.query(Right).filter(Right.user_id == user.id).delete()
        # Delete user
        db.session.delete(user)
        db.session.commit()
        flash(_('Benutzer {} gelöscht.'.format(user.username)))
        return redirect(url_for('users.userlist', page=1))
    return render_template('users/userpage.html', title=_("Benutzerübersicht - "), user=user, edit=edit, editform=editform, change2faform=change2faform, deleteform=deleteform, rights=rights)

# USERLIST
@bp.route('/userlist/<page>', methods=['GET'])
@login_required
def userlist(page):
    rights = get_user_rights()
    query = sa.Select(User).order_by(User.id)
    users = db.paginate(query, page=int(page), per_page=50, error_out=False)
    next_url = url_for('users.userlist', page=users.next_num) if users.has_next else None
    prev_url = url_for('users.userlist', page=users.prev_num) if users.has_prev else None
    return render_template('users/userlist.html', title=_("Benutzerliste - "), users=users.items, next_url=next_url, prev_url=prev_url, rights=rights, can_edit=rights['delete_users'])

# USER CREATION
@bp.route('/usercreate', methods=['GET', 'POST'])
@login_required
def usercreate():
    rights = get_user_rights()
    # Check access rights
    if not rights['create_users']:
        flash(_('Fehler: Keine Berechtigung zur Erstellung von Benutzern.'))
        return redirect(url_for('users.userlist', page=1))
    form = UserCreateForm()
    # Create new user
    if form.validate_on_submit():
        # Submit the user
        user = User(
            username=form.username.data,
            firstname=form.firstname.data,
            lastname=form.lastname.data,
            email=form.email.data,
            phone=form.phone.data,
            token_2fa=pyotp.random_base32()
        )
        db.session.add(user)
        db.session.commit()
        db.session.refresh(user)
        # Submit the user rights
        rights = Right(
            user_id=user.id,
            is_admin=form.is_admin.data,
            login_allowed=form.login_allowed.data,
            create_calendar_entry=form.create_calendar_entry.data,
            create_user=form.create_user.data,
            edit_user=form.edit_user.data,
            delete_user=form.delete_user.data,
            edit_rights=form.edit_rights.data,
            create_post=form.create_post.data,
            edit_foreign_post=form.edit_foreign_post.data,
            delete_foreign_post=form.delete_foreign_post.data
        )
        db.session.add(rights)
        db.session.commit()
        flash_message = _('Benutzer {} erstellt.'.format(user.username))

        # Create and send the registration token
        token = generate_token(form.email.data, current_app.config['SECRET_KEY'], 'email-registration')
        verify_url = url_for('auth.verify', token=token, _external=True)
        report = send_email(
            to=form.email.data,
            subject=_('Willkommen beim Olbers Planetarium'),
            template='auth/mail_registration',
            verify_url=verify_url
        )
        flash_message += report

        flash(flash_message)
        return redirect(url_for('users.userlist', page=1))
    return render_template('users/usercreate.html', title=_("Benutzer erstellen - "), form=form, rights=rights)

# USER AVATARS
@bp.route('/avatar/<path:filename>', methods=['GET'])
@login_required
def avatar(filename):
    return send_from_directory(current_app.config['UPLOAD_FOLDER'], path=filename)

# GET SOME SPECIFIC ACCESS RIGHTS
def get_user_rights():
    return {
        'create_users': current_user.check_right_or_admin('create_user'),
        'edit_users': current_user.check_right_or_admin('edit_user'),
        'delete_users': current_user.check_right_or_admin('delete_user'),
    }

app/templates/users/usercreate.html
{% extends 'users/usernav.html' %}
{% from 'bootstrap5/form.html' import render_field %}

{% block headline %}{{ _('Neuer Benutzeraccount') }}{% endblock %}

{% block content %}
<div class="container justify-content-center">
    <div class="card bg-complementary p-2" style="max-width: 1000px;">
        <div class="row justify-content-center">
            <img src="{{ url_for('static', filename='img/default_profile.png') }}" class="img-fluid" alt="{{ _('Neuer Benutzer') }}" style="max-width: 100px;">
        </div>
        <form action method="post" class="form row g-3" role="form">
        {{ form.csrf_token() }}
            <div class="col-md-12">
                {{ render_field(form.username) }}
            </div>
            <div class="col-md-6">
                {{ render_field(form.firstname) }}
            </div>
            <div class="col-md-6">
                {{ render_field(form.lastname) }}
            </div>
            <div class="col-md-12">
                {{ render_field(form.email) }}
            </div>
            <div class="col-md-12">
                {{ render_field(form.phone) }}
            </div>
            <div class="col-md-6">
                {{ render_field(form.login_allowed) }}
            </div>
            <div class="col-md-6">
                {{ render_field(form.is_admin) }}
            </div>
            <div class="col-md-3">
                {{ render_field(form.create_calendar_entry) }}
            </div>
            <div class="col-md-3">
                {{ render_field(form.create_user) }}
            </div>
            <div class="col-md-3">
                {{ render_field(form.edit_user) }}
            </div>
            <div class="col-md-3">
                {{ render_field(form.delete_user) }}
            </div>
            <div class="col-md-3">
                {{ render_field(form.edit_rights) }}
            </div>
            <div class="col-md-3">
                {{ render_field(form.create_post) }}
            </div>
            <div class="col-md-3">
                {{ render_field(form.edit_foreign_post) }}
            </div>
            <div class="col-md-3">
                {{ render_field(form.delete_foreign_post) }}
            </div>
            <div class="col-md-12">
                {{ render_field(form.submit) }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/users/userlist.html
{% extends 'users/usernav.html' %}

{% from 'bootstrap5/utils.html' import render_icon %}

{% block headline %}{{ _('Benutzerliste') }}{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row my-2 justify-content-center">
        <div class="col col-sm-4">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>{{ _('Benutzername') }}</th>
                        <th>{{ _('Vorname') }}</th>
                        <th>{{ _('Nachname') }}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                    <tr>
                        <td><a href="{{ url_for('users.userpage', user=user.id) }}">{{ user.username }}</a></td>
                        <td>{{ user.firstname }}</td>
                        <td>{{ user.lastname }}</td>
                        {% if can_edit %}<td><a href="{{ url_for('users.userpage', user=user.id, edit=1) }}" title="{{ _('Daten bearbeiten') }}"><span class="badge text-bg-secondary">{{ render_icon('pencil-fill') }}</span></a></td>{% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="row my-2 gx-5 justify-content-center">
        <div class="col col-sm-2">
            {% if prev_url %}
            <a href="{{ prev_url }}" class="btn btn-primarycontrast">{{ _('Vorherige Seite') }}</a>
            {% else %}
            <div style="display: inline-block;" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="{{ _('Keine weitere Seite vorhanden') }}">
                <button class="btn btn-primarycontrast" disabled>{{ _('Vorherige Seite') }}</button>
            </div>
            {% endif %}
        </div>
        <div class="col col-sm-2">
            {% if next_url %}
            <a href="{{ next_url }}" class="btn btn-primarycontrast float-end">{{ _('Nächste Seite') }}</a>
            {% else %}
            <div class="float-end" style="display: inline-block;" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="{{ _('Keine weitere Seite vorhanden') }}">
                <button class="btn btn-primarycontrast float-end" disabled>{{ _('Nächste Seite') }}</button>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
    const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
</script>
{% endblock %}

app/templates/users/usernav.html
{% extends 'main/main.html' %}
{% from 'bootstrap5/nav.html' import render_nav_item %}

{% block headline %}{{ _('Benutzer') }}{% endblock %}

{% block divider %}
{{ super() }}
<div class="container">
    <nav class="navbar navbar-expand-lg my-1" data-bs-theme="dark" aria-label='secondary'>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav me-auto border-top border-secondary">
                <li class="nav-item bg-primarycontrast rounded-bottom mx-1">
                    {{ render_nav_item('users.userpage', _('Übersicht')) }}
                </li>
                <li class="nav-item bg-primarycontrast rounded-bottom mx-1">
                    {{ render_nav_item('users.userpage', _('Eigene Daten ändern'), edit=1) }}
                </li>
                <li class="nav-item bg-primarycontrast rounded-bottom mx-1">
                    {{ render_nav_item('users.userlist', _('Benutzerliste'), page=0) }}
                </li>
                {% if rights['create_users'] %}
                <li class="nav-item bg-primarycontrast rounded-bottom mx-1">
                    {{ render_nav_item('users.usercreate', _('Neuer Benutzeraccount')) }}
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>
{% endblock %}

app/templates/users/userpage.html
{% extends 'users/usernav.html' %}
{% from 'bootstrap5/form.html' import render_form %}

{% block headline %}{{ _('Benutzer') }}{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row my-2 justify-content-center">
        <div class="card" style="max-width: 800px;">
            <div class="row g-0">
                <div class="col-md-4">
                <img src="{% if user.avatar %}{{ url_for('users.avatar', filename=user.avatar) }}{% else %}{{ url_for('static', filename='img/default_profile.png') }}{% endif %}" class="img-fluid rounded-start" alt="{{ user.username }}">
                </div>
                <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{ user.username }}</h5>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">{{ _('Vorname:') }} {{ user.firstname }}</li>
                        <li class="list-group-item">{{ _('Nachname:') }} {{ user.lastname }}</li>
                        <li class="list-group-item">{{ _('E-Mail:') }} {{ user.email }}</li>
                        <li class="list-group-item">{{ _('Telefon:') }} {{ user.phone }}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% if edit %}
    <div class="row my-2 justify-content-center">
        <div class="card bg-complementary" style="max-width: 800px;">
            <div class="card-body">
                <h5 class="card-title">{{ _('Bearbeiten:') }}</h5>
                {{ render_form(editform) }}
                <br />
                <h5 class="card-title">{{ _('Authentifizierung:') }}</h5>
                <p class="card-text">{{ _('Zwei-Faktor-Authentifizierung neu einrichten: ') }}</p>
                <a href="{{ url_for('auth.setup_2fa', user=user.id) }}"><button class="btn btn-primary btn-md">Hier klicken</button></a>
            </div>
        </div>
    </div>
    <div class="row my-2 justify-content-center">
        <div class="card bg-warning" style="max-width: 800px;">
            <div class="card-body">
                <h5 class="card-title">{{ _('Neues Geheimnis für Zwei-Faktor-Authentifizierung generieren:') }}</h5>
                <p class="card-text">{{ _('Achtung! Hiernach wird die Zwei-Faktor-Authentifizierung zunächst einmal deaktiviert und muss neu eingerichtet werden!') }}</p>
                {{ render_form(change2faform) }}
            </div>
        </div>
    </div>
    <div class="row my-2 justify-content-center">
        <div class="card bg-danger" style="max-width: 800px;">
            <div class="card-body">
                <h5 class="card-title">{{ _('Benutzer löschen:') }}</h5>
                {{ render_form(deleteform) }}
            </div>
        </div>
    </div>
{% endif %}
</div>
{% endblock %}